# Generated by Django 5.1.6 on 2025-07-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_supabase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supabase_uid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
