# Generated by Django 5.1.6 on 2025-09-30 17:01

import users.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_supabase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='users/default.jpg', upload_to=users.utilities.SafeFileName('users')),
        ),
    ]
