# Generated by Django 5.1.6 on 2025-08-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_message_media_message_parent_message_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
