# Generated by Django 5.1.6 on 2025-09-30 17:01

import users.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_message_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(null=True, upload_to=users.utilities.SafeFileName('messages')),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/default.jpg', upload_to=users.utilities.SafeFileName('projects')),
        ),
    ]
